import { VISUAL_TYPES, RENDERERS } from "./visualTypes.js";

// Single source of truth for "which renderer draws this kind of visual".
// Extend this map when a new visual type is introduced — nothing else in
// the app needs to change.
export const VISUAL_TYPE_TO_RENDERER = {
  [VISUAL_TYPES.FLOWCHART]: RENDERERS.MERMAID,
  [VISUAL_TYPES.PROCESS]: RENDERERS.MERMAID,
  [VISUAL_TYPES.CONCEPT_MAP]: RENDERERS.MERMAID,
  [VISUAL_TYPES.SEQUENCE]: RENDERERS.MERMAID,

  [VISUAL_TYPES.ARCHITECTURE]: RENDERERS.REACT_FLOW,
  [VISUAL_TYPES.ALGORITHM]: RENDERERS.REACT_FLOW,
  [VISUAL_TYPES.DATA_STRUCTURE]: RENDERERS.REACT_FLOW,

  [VISUAL_TYPES.MATH_GRAPH]: RENDERERS.JSXGRAPH,
  [VISUAL_TYPES.GEOMETRY]: RENDERERS.JSXGRAPH,

  [VISUAL_TYPES.SIMULATION]: RENDERERS.P5,
  [VISUAL_TYPES.SIMULATION_3D]: RENDERERS.THREE,

  [VISUAL_TYPES.NETWORK]: RENDERERS.CYTOSCAPE,
  [VISUAL_TYPES.KNOWLEDGE_GRAPH]: RENDERERS.CYTOSCAPE,

  [VISUAL_TYPES.TIMELINE]: RENDERERS.D3,
  [VISUAL_TYPES.DATA_VISUALIZATION]: RENDERERS.D3,
};

/** Looks up the renderer key for a visual type, defaulting to Mermaid. */
export function getRendererForType(visualType) {
  return VISUAL_TYPE_TO_RENDERER[visualType] || RENDERERS.MERMAID;
}
